### ISSUE TITLE
Datenbankmodel erstellen

### ISSUE THREAD

**Issue by Hitman29413** [Hitman29413/Zeiterfassung#2]

**Comment by apieper** [comment]
aktueller Aufbau des DB-Modells mit Orientierung am Format der T-O-M - Daten:

------------------------
| working time        |
|-----------------------|
| id                  (int)   |
| calendarWeek   (int) |
| date            (text)      |        
| startTime     (timestamp) |
| endTime      (timestamp) | 
| breakTime    (long)    |
| workingHours  (float)  |
| timeDiff       (float)    |
| absence      (text)   |
| comment     (text)   |
----------------------------
